### ISSUE TITLE
1.1.x render disk cache breaks every SVG on iOS/JVM with Skiko 0.150.x (Image.encodeToData signature changed)

### ISSUE THREAD

**Issue by devunt** [hash-sequence/coil-resvg#4]
## Summary

After upgrading from 1.0.0 to 1.1.1, every SVG silently stops rendering on iOS and desktop (JVM) when the app resolves Skiko 0.150.1 (Compose Multiplatform 1.12.0 / Coil 3.6.0). Android is unaffected. There are no logs unless a Coil `Logger` is attached, because the failure is thrown as an `Error`, not an `Exception`.

## Environment

- coil-resvg 1.1.1 (also applies to 1.1.0, which introduced the render cache)
- Coil 3.6.0, Compose Multiplatform 1.12.0, Skiko 0.150.1, Kotlin 2.4.20-RC2
- Affected: iOS (arm64), JVM desktop. Not affected: Android.

## Root cause

The render disk cache added in 1.1.0 encodes the rendered bitmap with `org.jetbrains.skia.Image.encodeToData(EncodedImageFormat, Int)` (`ResvgDecoder.ios.kt` / `ResvgDecoder.jvm.kt`, `encodeCachedBitmap`).

Skiko 0.150.x added a third parameter (`pngCompressionLevel`) to that function, and since it is a Kotlin default parameter (no `@JvmOverloads`), the old two-argument binary no longer exists:

```
# skiko-awt 0.144.6
public final org.jetbrains.skia.Data encodeToData(org.jetbrains.skia.EncodedImageFormat, int);

# skiko-awt 0.150.1
public final org.jetbrains.skia.Data encodeToData(org.jetbrains.skia.EncodedImageFormat, int, int);

# coil-resvg-jvm 1.1.1, ResvgDecoder_jvmKt.encodeCachedBitmap (javap -c)
invokevirtual org/jetbrains/skia/Image.encodeToData:(Lorg/jetbrains/skia/EncodedImageFormat;I)Lorg/jetbrains/skia/Data;
```

On JVM this throws `java.lang.NoSuchMethodError: 'org.jetbrains.skia.Data org.jetbrains.skia.Image.encodeToData(org.jetbrains.skia.EncodedImageFormat, int)'`. On iOS the same call is resolved through Kotlin/Native partial linkage and throws `IrLinkageError` at the call site.

Both are `Error` subclasses, so the `catch (_: Exception)` guards in `writeToDiskCache` do not catch them. The error escapes `ResvgDecoder.decode()` after the SVG was already rendered successfully, Coil turns it into an `ErrorResult`, and nothing is drawn. Android uses `android.graphics.Bitmap.compress` for the cache, which is why it keeps working.

## Reproduction

```kotlin
val loader = ImageLoader.Builder(PlatformContext.INSTANCE)
    .diskCache(DiskCache.Builder().directory(tmpDir).build())
    .components { add(ResvgDecoder.Factory()) }   // diskCacheEnabled = true (default)
    .build()

val result = loader.execute(ImageRequest.Builder(PlatformContext.INSTANCE).data(anySvgFile).size(360, 48).build())
// JVM + Skiko 0.150.1: ErrorResult(NoSuchMethodError: Image.encodeToData(EncodedImageFormat, int))
```

With `ResvgDecoder.Factory(diskCacheEnabled = false)` the same request succeeds and the bitmap is fully rendered, so the resvg side is fine.

## Workaround

`ResvgDecoder.Factory(diskCacheEnabled = false)`.

## Suggested fix

- Rebuild against Skiko 0.150.x (or call `encodeToData(format, quality, pngCompressionLevel)` explicitly / pin a compatible Skiko range in the published metadata).
- Consider catching `Throwable` (or at least `Error`) around the cache encode/write path, since a cache write failure should not discard an already rendered image.

Thanks for the library!

**Comment by petrichor** [comment]
Thanks for reporting! Fixed in v1.1.2 by moving PNG cache encoding to Rust, avoiding the Skiko API incompatibility. Please try upgrading and let me know if the issue persists.
